apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbgs-controller-sa
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: rbgs-controller
    app.kubernetes.io/name: rbgs
    app.kubernetes.io/managed-by: {{ .Release.Service }}
