#!/usr/bin/env bash
# L3 live layer for PR#418 finding F1.
#
# Proves the real-world consequence of narrowing the shared headless Service selector to
# component-name=leader on a role that runs on a StatefulSet.
#
# The cluster's installed controller is PRE-PR (v0.8.0-47cfe17), so arm A shows the CURRENT
# production behaviour. Arm B applies, by hand, exactly the selector that PR#418's
# svc_reconciler generates for the same role (proved at L1) over the very same real pods, and
# measures the endpoints. Nothing cluster-scoped is touched and no second controller is run.
#
# Safety: everything lives in a single dedicated namespace which is deleted on exit.
set -uo pipefail

NS="${NS:-pr418-f1-$(date +%s)}"
KEEP="${KEEP:-0}"
RBG_NAME=pr418-sts

cleanup() {
  if [ "$KEEP" = "1" ]; then
    echo "[cleanup] KEEP=1, leaving namespace $NS in place"
    return
  fi
  echo "[cleanup] deleting namespace $NS"
  kubectl delete ns "$NS" --wait=false >/dev/null 2>&1
}
trap cleanup EXIT

echo "=== PR#418 F1 live verification ==="
echo "namespace: $NS"
kubectl create ns "$NS" >/dev/null

# ---------------------------------------------------------------------------
# A role with a leaderWorkerPattern pinned to the StatefulSet workload type, with
# sharedServiceSelection deliberately UNSET -- the only shape the restored CEL rule admits
# for this workload type.
# ---------------------------------------------------------------------------
cat <<YAML | kubectl apply -f - >/dev/null
apiVersion: workloads.x-k8s.io/v1alpha2
kind: RoleBasedGroup
metadata:
  name: $RBG_NAME
  namespace: $NS
spec:
  roles:
    - name: worker
      replicas: 2
      annotations:
        rbg.workloads.x-k8s.io/role-workload-type: apps/v1/StatefulSet
      leaderWorkerPattern:
        size: 2
        template:
          spec:
            containers:
              - name: nginx
                image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
                imagePullPolicy: IfNotPresent
YAML

echo
echo "--- the API server ACCEPTED the role (CEL rule does not fire on an unset field) ---"
kubectl get rbg -n "$NS" "$RBG_NAME" -o jsonpath='{.spec.roles[0].leaderWorkerPattern.sharedServiceSelection}' \
  | sed 's/^$/<unset>/'
echo

echo "--- waiting for pods to become Ready ---"
kubectl wait --for=condition=Ready pod -n "$NS" -l rbg.workloads.x-k8s.io/group-name="$RBG_NAME" \
  --timeout=180s || { echo "PODS DID NOT BECOME READY"; kubectl get pod -n "$NS" -o wide; }

echo
echo "--- pod labels: does any pod carry component-name? ---"
kubectl get pod -n "$NS" -l rbg.workloads.x-k8s.io/group-name="$RBG_NAME" \
  -o custom-columns='POD:.metadata.name,COMPONENT:.metadata.labels.rbg\.workloads\.x-k8s\.io/component-name,IP:.status.podIP'

SVC=$(kubectl get svc -n "$NS" -o jsonpath='{.items[0].metadata.name}')
echo
echo "=== ARM A: selector generated by the INSTALLED (pre-PR) controller ==="
echo "service: $SVC"
kubectl get svc -n "$NS" "$SVC" -o jsonpath='{.spec.selector}'; echo
A_COUNT=$(kubectl get endpointslice -n "$NS" -l kubernetes.io/service-name="$SVC" \
  -o jsonpath='{range .items[*]}{range .endpoints[*]}{.addresses[0]}{"\n"}{end}{end}' | grep -c . )
echo "ready endpoint addresses: $A_COUNT"

# ---------------------------------------------------------------------------
# ARM B: the selector PR#418 generates for this same role (proved at L1):
#   {group-name, role-name, component-name=leader}
# Applied as a separate Service so the installed controller does not fight the change.
# ---------------------------------------------------------------------------
echo
echo "=== ARM B: selector generated by PR#418 for the SAME role ==="
cat <<YAML | kubectl apply -f - >/dev/null
apiVersion: v1
kind: Service
metadata:
  name: pr418-head-selector
  namespace: $NS
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    rbg.workloads.x-k8s.io/group-name: $RBG_NAME
    rbg.workloads.x-k8s.io/role-name: worker
    rbg.workloads.x-k8s.io/component-name: leader
YAML

kubectl get svc -n "$NS" pr418-head-selector -o jsonpath='{.spec.selector}'; echo
sleep 5
B_COUNT=$(kubectl get endpointslice -n "$NS" -l kubernetes.io/service-name=pr418-head-selector \
  -o jsonpath='{range .items[*]}{range .endpoints[*]}{.addresses[0]}{"\n"}{end}{end}' | grep -c . )
echo "ready endpoint addresses: $B_COUNT"

echo
echo "--- DNS resolution of the PR#418-selector service from inside the cluster ---"
kubectl run pr418-dns --rm -i --restart=Never -n "$NS" \
  --image=anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6 --command -- \
  sh -c "echo -n 'pr418-head-selector -> '; getent hosts pr418-head-selector.$NS.svc.cluster.local || echo 'NXDOMAIN / no address';
         echo -n '$SVC (pre-PR selector) -> '; getent hosts $SVC.$NS.svc.cluster.local || echo 'NXDOMAIN / no address'" \
  2>/dev/null || echo "(dns probe pod failed to run)"

echo
echo "=========================== VERDICT ==========================="
echo "pre-PR selector  -> $A_COUNT endpoint address(es)"
echo "PR#418 selector  -> $B_COUNT endpoint address(es)"
if [ "$A_COUNT" -gt 0 ] && [ "$B_COUNT" -eq 0 ]; then
  echo "F1 CONFIRMED: PR#418's selector drops every endpoint for a StatefulSet-backed"
  echo "leaderWorkerPattern role, because no StatefulSet pod carries component-name=leader."
else
  echo "F1 NOT REPRODUCED as predicted (A=$A_COUNT B=$B_COUNT) -- inspect above."
fi
echo "==============================================================="
