/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CrashedPodApplyConfiguration represents a declarative configuration of the CrashedPod type for use
// with apply.
type CrashedPodApplyConfiguration struct {
	PodName         *string  `json:"podName,omitempty"`
	NodeName        *string  `json:"nodeName,omitempty"`
	Container       *string  `json:"container,omitempty"`
	ExitCode        *int32   `json:"exitCode,omitempty"`
	Reason          *string  `json:"reason,omitempty"`
	FinishedAt      *v1.Time `json:"finishedAt,omitempty"`
	RestartCount    *int32   `json:"restartCount,omitempty"`
	LikelyRootCause *bool    `json:"likelyRootCause,omitempty"`
}

// CrashedPodApplyConfiguration constructs a declarative configuration of the CrashedPod type for use with
// apply.
func CrashedPod() *CrashedPodApplyConfiguration {
	return &CrashedPodApplyConfiguration{}
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *CrashedPodApplyConfiguration) WithPodName(value string) *CrashedPodApplyConfiguration {
	b.PodName = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *CrashedPodApplyConfiguration) WithNodeName(value string) *CrashedPodApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithContainer sets the Container field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Container field is set to the value of the last call.
func (b *CrashedPodApplyConfiguration) WithContainer(value string) *CrashedPodApplyConfiguration {
	b.Container = &value
	return b
}

// WithExitCode sets the ExitCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExitCode field is set to the value of the last call.
func (b *CrashedPodApplyConfiguration) WithExitCode(value int32) *CrashedPodApplyConfiguration {
	b.ExitCode = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *CrashedPodApplyConfiguration) WithReason(value string) *CrashedPodApplyConfiguration {
	b.Reason = &value
	return b
}

// WithFinishedAt sets the FinishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FinishedAt field is set to the value of the last call.
func (b *CrashedPodApplyConfiguration) WithFinishedAt(value v1.Time) *CrashedPodApplyConfiguration {
	b.FinishedAt = &value
	return b
}

// WithRestartCount sets the RestartCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartCount field is set to the value of the last call.
func (b *CrashedPodApplyConfiguration) WithRestartCount(value int32) *CrashedPodApplyConfiguration {
	b.RestartCount = &value
	return b
}

// WithLikelyRootCause sets the LikelyRootCause field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LikelyRootCause field is set to the value of the last call.
func (b *CrashedPodApplyConfiguration) WithLikelyRootCause(value bool) *CrashedPodApplyConfiguration {
	b.LikelyRootCause = &value
	return b
}
