/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// RestartPolicyConfigApplyConfiguration represents a declarative configuration of the RestartPolicyConfig type for use
// with apply.
type RestartPolicyConfigApplyConfiguration struct {
	RebuildDelaySeconds    *int32 `json:"rebuildDelaySeconds,omitempty"`
	MaxConsecutiveRebuilds *int32 `json:"maxConsecutiveRebuilds,omitempty"`
}

// RestartPolicyConfigApplyConfiguration constructs a declarative configuration of the RestartPolicyConfig type for use with
// apply.
func RestartPolicyConfig() *RestartPolicyConfigApplyConfiguration {
	return &RestartPolicyConfigApplyConfiguration{}
}

// WithRebuildDelaySeconds sets the RebuildDelaySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RebuildDelaySeconds field is set to the value of the last call.
func (b *RestartPolicyConfigApplyConfiguration) WithRebuildDelaySeconds(value int32) *RestartPolicyConfigApplyConfiguration {
	b.RebuildDelaySeconds = &value
	return b
}

// WithMaxConsecutiveRebuilds sets the MaxConsecutiveRebuilds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxConsecutiveRebuilds field is set to the value of the last call.
func (b *RestartPolicyConfigApplyConfiguration) WithMaxConsecutiveRebuilds(value int32) *RestartPolicyConfigApplyConfiguration {
	b.MaxConsecutiveRebuilds = &value
	return b
}
