/*
Copyright 2026 The RBG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RoleInstanceCrashInfoApplyConfiguration represents a declarative configuration of the RoleInstanceCrashInfo type for use
// with apply.
type RoleInstanceCrashInfoApplyConfiguration struct {
	ObservedTime *v1.Time                       `json:"observedTime,omitempty"`
	Pods         []CrashedPodApplyConfiguration `json:"pods,omitempty"`
}

// RoleInstanceCrashInfoApplyConfiguration constructs a declarative configuration of the RoleInstanceCrashInfo type for use with
// apply.
func RoleInstanceCrashInfo() *RoleInstanceCrashInfoApplyConfiguration {
	return &RoleInstanceCrashInfoApplyConfiguration{}
}

// WithObservedTime sets the ObservedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedTime field is set to the value of the last call.
func (b *RoleInstanceCrashInfoApplyConfiguration) WithObservedTime(value v1.Time) *RoleInstanceCrashInfoApplyConfiguration {
	b.ObservedTime = &value
	return b
}

// WithPods adds the given value to the Pods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pods field.
func (b *RoleInstanceCrashInfoApplyConfiguration) WithPods(values ...*CrashedPodApplyConfiguration) *RoleInstanceCrashInfoApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPods")
		}
		b.Pods = append(b.Pods, *values[i])
	}
	return b
}
